// generated by stringer -type=tokenType; DO NOT EDIT

package gocalc

import "fmt"

const _tokenType_name = "tokenErrortokenEOFtokenIdentifiertokenTruetokenFalsetokenInttokenFloattokenLeftParentokenRightParentokenCommatokenLogicalNottokenBitwiseNottokenBinarytokenStartokenSlashtokenPercenttokenPlustokenMinustokenLeftShifttokenRightShifttokenLessThantokenLessOrEqualtokenGreaterThantokenGreaterOrEqualtokenEqualtokenNotEqualtokenBitwiseAndtokenBitwiseXortokenBitwiseOrtokenLogicalAndtokenLogicalOr"

var _tokenType_index = [...]uint16{0, 10, 18, 33, 42, 52, 60, 70, 84, 99, 109, 124, 139, 150, 159, 169, 181, 190, 200, 214, 229, 242, 258, 274, 293, 303, 316, 331, 346, 360, 375, 389}

func (i tokenType) String() string {
	if i < 0 || i+1 >= tokenType(len(_tokenType_index)) {
		return fmt.Sprintf("tokenType(%d)", i)
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
