// generated by stringer -type=tokenType; DO NOT EDIT

package gocalc

import "fmt"

const _tokenType_name = "tokenErrortokenWhitespacetokenEOFtokenIdentifiertokenTruetokenFalsetokenInttokenFloattokenLeftParentokenRightParentokenCommatokenLogicalNottokenBitwiseNottokenBinarytokenStartokenSlashtokenPercenttokenPlustokenMinustokenLeftShifttokenRightShifttokenLessThantokenLessOrEqualtokenGreaterThantokenGreaterOrEqualtokenEqualtokenNotEqualtokenBitwiseAndtokenBitwiseXortokenBitwiseOrtokenLogicalAndtokenLogicalOr"

var _tokenType_index = [...]uint16{0, 10, 25, 33, 48, 57, 67, 75, 85, 99, 114, 124, 139, 154, 165, 174, 184, 196, 205, 215, 229, 244, 257, 273, 289, 308, 318, 331, 346, 361, 375, 390, 404}

func (i tokenType) String() string {
	if i < 0 || i+1 >= tokenType(len(_tokenType_index)) {
		return fmt.Sprintf("tokenType(%d)", i)
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
